export const USER_LOADING = "USER_LOADING";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const LOG_OUT = "LOG_OUT";
export const GET_USERS = "GET_USERS";

export const FETCH_ERROR = "FETCH_ERROR";

export const PLACES_LOADING = "PLACES_LOADING";
export const SUCCESS_GET_PLACES = "SUCCESS_GET_PLACES";
export const SUCCESS_GET_PLACE = "SUCCESS_GET_PLACE";
export const UPDATE_PLACE_SUCCESS = "UPDATE_PLACE_SUCCESS";
export const ADD_PLACE_SUCCESS = "ADD_PLACE_SUCCESS";
export const DELETE_PLACE_SUCCESS = "DELETE_PLACE_SUCCESS";
